### ISSUE TITLE
Cannot find module node-sass

### ISSUE THREAD

**Issue by BetterAutomations** [gonzad77/ionic4-wordpress#1]
If I don't upgrading node-sass to 7.0.1 in package-lock.json, npm install fails. When I upgrade, I get the following error.

```
CBdeV@DAD-E5430 /cygdrive/c/Users/CBdeV/Documents/ionic4-wordpress
$ ionic serve
> ng.cmd run app:serve --host=localhost --port=8100
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...
[INFO] Waiting for connectivity with ng...

[INFO] Development server running!

       Local: http://localhost:8100

       Use Ctrl+C to quit this process

[INFO] Browser window opened to http://localhost:8100!

[ng] i ｢wdm｣: wait until bundle finished: /
[ng] Date: 2022-01-27T15:56:38.403Z
[ng] Hash: 259805dacfff0dd4fd01
[ng] Time: 45440ms
[ng]
[ng] ERROR in ./src/global.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-lo
ader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/global.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\loadLoader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\LoaderRunner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModule.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModuleFactory.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\Compiler.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\webpack.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\architect.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\architect-command.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\commands\build-impl.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\utilities\json-schema.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\command-runner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\cli\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\init.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\bin\ng
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
[ng]     at Module.require (internal/modules/cjs/loader.js:961:19)
[ng]     at require (internal/modules/cjs/helpers.js:92:18)
[ng]     at Object.sassLoader (C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js:46:72)
[ng] ERROR in ./src/theme/variables.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/p
ostcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/theme/variables.scss)
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\loadLoader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\LoaderRunner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModule.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModuleFactory.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\Compiler.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\webpack.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\architect.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\architect-command.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\commands\build-impl.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\utilities\json-schema.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\command-runner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\cli\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\init.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\bin\ng
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
[ng]     at Module.require (internal/modules/cjs/loader.js:961:19)
[ng]     at require (internal/modules/cjs/helpers.js:92:18)
[ng]     at Object.sassLoader (C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js:46:72)
[ng] ERROR in ./src/app/pages/home/home.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\loadLoader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\LoaderRunner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModule.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModuleFactory.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\Compiler.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\webpack.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\architect.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\architect-command.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\commands\build-impl.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\utilities\json-schema.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\command-runner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\cli\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\init.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\bin\ng
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
[ng]     at Module.require (internal/modules/cjs/loader.js:961:19)
[ng]     at require (internal/modules/cjs/helpers.js:92:18)
[ng]     at Object.sassLoader (C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js:46:72)
[ng] ERROR in ./src/app/pages/login/login.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\loadLoader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\LoaderRunner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModule.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModuleFactory.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\Compiler.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\webpack.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\architect.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\architect-command.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\commands\build-impl.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\utilities\json-schema.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\command-runner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\cli\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\init.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\bin\ng
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
[ng]     at Module.require (internal/modules/cjs/loader.js:961:19)
[ng]     at require (internal/modules/cjs/helpers.js:92:18)
[ng]     at Object.sassLoader (C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js:46:72)
[ng] ERROR in ./src/app/pages/post/post.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\loadLoader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\LoaderRunner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModule.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModuleFactory.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\Compiler.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\webpack.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\architect.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\architect-command.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\commands\build-impl.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\utilities\json-schema.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\command-runner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\cli\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\init.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\bin\ng
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
[ng]     at Module.require (internal/modules/cjs/loader.js:961:19)
[ng]     at require (internal/modules/cjs/helpers.js:92:18)
[ng]     at Object.sassLoader (C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js:46:72)
[ng] ERROR in ./src/app/pages/register/register.page.scss
[ng] Module build failed (from ./node_modules/sass-loader/lib/loader.js):
[ng] Error: Cannot find module 'node-sass'
[ng] Require stack:
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\loadLoader.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\loader-runner\lib\LoaderRunner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModule.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\NormalModuleFactory.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\Compiler.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\webpack\lib\webpack.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\webpack\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-webpack\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\architect.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular-devkit\architect\src\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\architect-command.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\commands\build-impl.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\utilities\json-schema.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\models\command-runner.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\cli\index.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\lib\init.js
[ng] - C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\@angular\cli\bin\ng
[ng]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
[ng]     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
[ng]     at Module.require (internal/modules/cjs/loader.js:961:19)
[ng]     at require (internal/modules/cjs/helpers.js:92:18)
[ng]     at Object.sassLoader (C:\Users\CBdeV\Documents\ionic4-wordpress\node_modules\sass-loader\lib\loader.js:46:72)
[ng] chunk {common} common.js, common.js.map (common) 23.6 kB  [rendered]
[ng] chunk {main} main.js, main.js.map (main) 45.4 kB [initial] [rendered]
[ng] chunk {pages-home-home-module} pages-home-home-module.js, pages-home-home-module.js.map (pages-home-home-module) 16.8 kB  [rendered]
[ng] chunk {pages-login-login-module} pages-login-login-module.js, pages-login-login-module.js.map (pages-login-login-module) 15.5 kB  [rendered]
[ng] chunk {pages-post-post-module} pages-post-post-module.js, pages-post-post-module.js.map (pages-post-post-module) 26.6 kB  [rendered]
[ng] chunk {pages-register-register-module} pages-register-register-module.js, pages-register-register-module.js.map (pages-register-register-module) 1
6 kB  [rendered]
[ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
[ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 8.97 kB [entry] [rendered]
[ng] chunk {styles} styles.js, styles.js.map (styles) 23.8 kB [initial] [rendered]
[ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 4.43 MB [initial] [rendered]
[ng] i ｢wdm｣: Failed to compile.

```

**Comment by djabif** [comment]
Oh, this repo is not functional. 
Check the repo of this tutorial https://ionicthemes.com/tutorials/ionic-wordpress-integration
